version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HTTP_LISTEN_ADDRESS: ${HTTP_LISTEN_ADDRESS}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_DB_URL: ${MONGO_DB_URL}
      MONGO_DB_URL_TEST: ${MONGO_DB_URL_TEST}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_UPLOAD_FOLDER: ${CLOUDINARY_UPLOAD_FOLDER}
    ports:
      - "5000:5000"
    volumes:
      - .env:/app/.env  # Mount the .env file from the host to the container
