#!/bin/sh

# Generate .env file from environment variables
cat <<EOF > /app/.env
CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
CLOUDINARY_UPLOAD_FOLDER=$CLOUDINARY_UPLOAD_FOLDER
HTTP_LISTEN_ADDRESS=$HTTP_LISTEN_ADDRESS
JWT_SECRET=$JWT_SECRET
MONGO_DB_NAME=$MONGO_DB_NAME
MONGO_DB_URL=$MONGO_DB_URL
MONGO_DB_URL_TEST=$MONGO_DB_URL_TEST
EOF

# Execute the main application
exec "$@"
