name: Auto Merge PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.1'

      - name: Test
        run: go test ./...

      - name: Merge PR
        if: github.event.pull_request.mergeable_state == 'clean'
        uses: pascalgn/automerge-action@v0.14.3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "auto-merge,approved" # Specify your labels here
          MERGE_METHOD: "squash" # Choose merge method: merge, squash or rebase
          MERGE_RETRIES: "3"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REMOVE_LABELS: "auto-merge,approved"
