name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-container:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ndeta100/hotel-api:latest
            ndeta100/hotel-api:${{ github.sha }}
          build-args: |
            HTTP_LISTEN_ADDRESS=${{ secrets.HTTP_LISTEN_ADDRESS }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            MONGO_DB_URL=${{ secrets.MONGO_DB_URL }}
            MONGO_DB_URL_TEST=${{ secrets.MONGO_DB_URL_TEST }}
            MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}
            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            CLOUDINARY_UPLOAD_FOLDER=${{ secrets.CLOUDINARY_UPLOAD_FOLDER }}

      - name: Verify Docker Image
        run: |
          docker images ndeta100/hotel-api

      - name: Log out from Docker Hub
        run: docker logout
