on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
                ndeta100/hotel-api:latest
                ndeta100/hotel-api:${{ github.sha }}

      - name: Delete old containers
        uses: snok/container-retention-policy@v2.0.0
        with:
          image-names: "ndeta100/hotel-api"
          cut-off: A week ago UTC
          account-type: org
          org-name: ndeta100
          keep-at-least: 3
          skip-tags: latest, v*
          token: ${{ secrets.GH_PACKAGES_SECRET }}
